name: Latest blog post workflow
on:
  push:
    branches:
      - master
  schedule: # Run workflow automatically
    - cron: '0 9 1 * *' # Runs at 9:00, every first day of month
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://ygeunkim.github.io/publication/index.xml"