name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 9 1 * *' # Runs at 9:00, every first day of month
  push:
    branches:
      - master
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Journal articles
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: JOURNAL
          feed_list: "https://ygeunkim.github.io/publication-type/2/index.xml"
          template: "[$title]($url)"
      - name: Conferences
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: CONF
          feed_list: "https://ygeunkim.github.io/publication-type/1/index.xml"
          template: "[$title]($url)"
      - name: Posters
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: POSTER
          feed_list: "https://ygeunkim.github.io/publication-type/0/index.xml"
          template: "[$title]($url)"
      - name: Patents
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: PATENT
          feed_list: "https://ygeunkim.github.io/publication-type/8/index.xml"
          template: "[$title]($url)"