name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 9 1 * *' # Runs at 9:00, every first day of month
  push:
    branches:
      - master
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Journal articles
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: JOURNAL
          feed_list: "https://ygeunkim.github.io/publication-type/2/index.xml"
          template: "<tr><td><li><a href=$url>$title</a></li></td><td><a href='https://ygeunkim.github.io/publication/#2'><img src='https://img.shields.io/badge/Journal%20article-yellow.svg' alt='journal'></a></td></tr>"
      - name: Conferences
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: CONF
          feed_list: "https://ygeunkim.github.io/publication-type/1/index.xml"
          template: "<tr><td><li><a href=$url>$title</a></li></td><td><a href='https://ygeunkim.github.io/publication/#1'><img src='https://img.shields.io/badge/Conference%20paper-lightblue.svg' alt='conf'></a></td></tr>"
      - name: Posters
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: POSTER
          feed_list: "https://ygeunkim.github.io/publication-type/0/index.xml"
          template: "<tr><td><li><a href=$url>$title</a></li></td><td><a href='https://ygeunkim.github.io/publication/#0'><img src='https://img.shields.io/badge/Workshop%20%26%20poster-grey.svg' alt='poster'></a></td></tr>"
      - name: Patents
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: PATENT
          feed_list: "https://ygeunkim.github.io/publication-type/8/index.xml"
          template: "<tr><td><li><a href=$url>$title</a></li></td><td><a href='https://ygeunkim.github.io/publication/#8'><img src='https://img.shields.io/badge/Patent-lightgreen.svg' alt='patent'></a></td></tr>"